# Generated by Django 4.0.3 on 2022-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrm',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='chat_id'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='entry_date',
            field=models.DateField(default='2022-04-18', verbose_name='entry_date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercrm',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='telegram'),
        ),
    ]
