# Generated by Django 4.0.3 on 2022-04-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_usercrm_chat_id_workinghours_entry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='price_cost',
        ),
    ]
