# Generated by Django 4.0.3 on 2022-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_register_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercrm',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
