# Generated by Django 4.0.3 on 2022-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_master_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='step',
            field=models.IntegerField(default=60, verbose_name='step'),
        ),
    ]
