# Generated by Django 4.0.1 on 2022-04-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Стоимость', 'verbose_name_plural': 'Стоимость'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='usercrm',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='register',
            name='service',
        ),
        migrations.AlterField(
            model_name='register',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price', to='crm.price'),
        ),
    ]
