# Generated by Django 4.0.1 on 2022-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_master_options_alter_price_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='master',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='register',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='register',
            name='working_hour',
            field=models.ManyToManyField(to='crm.WorkingHours'),
        ),
    ]
