# Generated by Django 4.0.1 on 2022-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_master_register_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='working_hour',
            field=models.ManyToManyField(related_name='working_hours', to='crm.WorkingHours'),
        ),
    ]
