# Generated by Django 4.0.1 on 2022-04-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_register_working_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='register',
            name='working_hour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='working_hours', to='crm.workinghours'),
            preserve_default=False,
        ),
    ]
